# Generated by Django 3.2.7 on 2023-01-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('price', models.CharField(max_length=127, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('available', models.CharField(max_length=123, verbose_name='Наличие')),
            ],
            options={
                'verbose_name': 'Электростанция',
                'verbose_name_plural': 'Электростанции',
            },
        ),
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('price', models.CharField(max_length=127, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('available', models.CharField(max_length=123, verbose_name='Наличие')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
            },
        ),
    ]
