version: "3"

services:
  
  db:
    container_name: E-motorsDB
    image: postgres:12.0-alpine
    volumes:
      - postgres_data/:/var/lib/postgresql/data
    networks:
      - my-network
    env_file:
      - ./.env
  
  web:
    container_name: E-motors
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./media/:/media
      - ./static/:/static
      - ./:/app
    entrypoint: ./wsgi-entrypoint.sh
    networks:
      - my-network
    depends_on:
      - db
  
  redis:
    container_name: redis_for_send_gmaill
    image: redis
    networks:
      - my-network
      
  celery:
    container_name: E-motorsCel
    build:
      context: .
    restart: always
    command: sh -c "celery -A core worker -l INFO"
    volumes:
      - ./:/app  
    depends_on:
      - web
    networks:
      - my-network   


volumes:
  media:
  static:
  postgres_data:

networks:
  my-network:




