# Generated by Django 3.2.7 on 2023-01-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Модель байка')),
                ('available', models.CharField(max_length=127, verbose_name='Наличие/Под заказ')),
                ('torque', models.CharField(max_length=127, verbose_name='Крутящий момент Нм')),
                ('max_speed', models.CharField(max_length=127, verbose_name='Максимальная скорость')),
                ('mileage', models.CharField(max_length=127, verbose_name='Пробег')),
                ('year_release', models.CharField(max_length=127, verbose_name='Год выпуска')),
                ('battery_capacity', models.CharField(max_length=127, verbose_name='Емкость батареи')),
                ('price', models.CharField(max_length=127, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Модель машины')),
                ('available', models.CharField(max_length=127, verbose_name='Наличие/Под заказ')),
                ('torque', models.CharField(max_length=127, verbose_name='Крутящий момент Нм')),
                ('max_speed', models.CharField(max_length=127, verbose_name='Максимальная скорость')),
                ('type_kuz', models.CharField(max_length=127, verbose_name='Тип кузова')),
                ('type_priv', models.CharField(max_length=127, verbose_name='Тип привода')),
                ('mileage', models.CharField(max_length=127, verbose_name='Пробег')),
                ('year_release', models.CharField(max_length=127, verbose_name='Год выпуска')),
                ('battery_capacity', models.CharField(max_length=127, verbose_name='Емкость батареи')),
                ('price', models.CharField(max_length=127, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='OtherTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Модель эл.транспорта')),
                ('available', models.CharField(max_length=127, verbose_name='Наличие/Под заказ')),
                ('torque', models.CharField(max_length=127, verbose_name='Крутящий момент Нм')),
                ('max_speed', models.CharField(max_length=127, verbose_name='Максимальная скорость')),
                ('mileage', models.CharField(max_length=127, verbose_name='Пробег')),
                ('year_release', models.CharField(max_length=127, verbose_name='Год выпуска')),
                ('battery_capacity', models.CharField(max_length=127, verbose_name='Емкость батареи')),
                ('price', models.CharField(max_length=127, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
